version: '3.3'
services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - salade-network
    volumes:
      - /home/debian/tournoisalade/nginx/conf/:/etc/nginx/conf.d/:ro
      - /home/debian/tournoisalade/certbot/conf/:/etc/letsencrypt
      - /home/debian/tournoisalade/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/debian/tournoisalade/certbot/conf/:/etc/letsencrypt/
      - /home/debian/tournoisalade/certbot/www:/var/www/certbot/

  salade:
    image: tournoisalade:prod
    container_name: salade
    ports:
      - 5000:5000
    networks:
      - salade-network
    volumes:
      - /home/debian/tournoisalade/db:/app/wwwroot/db
      - /etc/localtime:/etc/localtime:ro

networks:
    salade-network:
      name: salade-network

