version: '3.3'
services:
  salade:
    image: tournoisalade:prod
    container_name: salade
    ports:
      - 443:443
      - 80:80
    volumes:
      - /home/debian/sites/tournoisalade/install/tournament.json:/app/wwwroot/db/tournament.json:ro
      - /etc/localtime:/etc/localtime:ro

